DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS item_request;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS booking;

    CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    email varchar(320),
    CONSTRAINT UQ_EMAIL UNIQUE (email)
);

    CREATE TABLE IF NOT EXISTS item_request
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200),
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    creation_date timestamp
);

    CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(200),
    available bool,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES item_request(id)
);

    CREATE TABLE IF NOT EXISTS booking
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date date,
    end_date date,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status varchar(30)
);

